# -*- coding: utf-8 -*-
"""FemaData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-siRt77p2h7PLXXGAIGBXRaMxt3Q5klk
"""

import requests
import pandas as pd
import os
import time

# --- SETTINGS ---
API_KEY = "fj0xunVdoRcmeloQHEgFkci8g6O2qiIslDlRyXP1"
DOCKET_ID = "DHS-2025-0013"
OUTPUT_CSV = "DHS_2025_0013_full_comments_with_pdfs.csv"
ATTACHMENT_FOLDER = "attachments"
os.makedirs(ATTACHMENT_FOLDER, exist_ok=True)

# --- Step 1: Get up to 500 comment IDs ---
comment_ids = []
params = {
    "filter[docketId]": DOCKET_ID,
    "api_key": API_KEY,
    "page[size]": 250
}
print("🔍 Collecting comment IDs...")

BASE_URL = "https://api.regulations.gov/v4/comments"
while len(comment_ids) < 500:
    r = requests.get(BASE_URL, params=params)
    data = r.json()
    for item in data.get("data", []):
        comment_ids.append(item["id"])
        if len(comment_ids) >= 500:
            break
    next_link = data.get("links", {}).get("next")
    if not next_link:
        break
    BASE_URL = next_link
    params = {}

print(f"✅ Collected {len(comment_ids)} IDs. Fetching full details...")

# --- Step 2: Get full details + attachments ---
results = []

for i, cid in enumerate(comment_ids):
    url = f"https://api.regulations.gov/v4/comments/{cid}?include=attachments&api_key={API_KEY}"
    r = requests.get(url)
    if r.status_code != 200:
        print(f"❌ Failed to fetch: {cid}")
        continue

    data = r.json()
    attr = data.get("data", {}).get("attributes", {})
    comment_text = attr.get("comment", "").strip()
    submitter = attr.get("submitterName")
    date = attr.get("postedDate")
    org = attr.get("organization")

    # --- Step 3: Check for attachments ---
    pdf_path = ""
    if "See attached file" in comment_text and "included" in data:
        for item in data["included"]:
            if item["type"] == "attachments":
                files = item["attributes"].get("fileFormats", [])
                for file in files:
                    if file["format"] == "pdf":
                        file_url = file["fileUrl"]
                        file_name = f"{cid}_{item['id']}.pdf"
                        local_path = os.path.join(ATTACHMENT_FOLDER, file_name)
                        try:
                            file_data = requests.get(file_url)
                            with open(local_path, "wb") as f:
                                f.write(file_data.content)
                            pdf_path = local_path
                            print(f"📎 Downloaded {file_name}")
                        except Exception as e:
                            print(f"❌ Failed to download {file_url}: {e}")
                        break

    results.append({
        "comment_id": cid,
        "submitted_date": date,
        "submitter": submitter,
        "organization": org,
        "comment": comment_text,
        "pdf_file_path": pdf_path
    })

    time.sleep(0.1)

# --- Step 4: Save everything ---
df = pd.DataFrame(results)
df.to_csv(OUTPUT_CSV, index=False)
print(f"✅ Done! {len(df)} records saved to {OUTPUT_CSV}")